name: generate-and-push-documentation
on:
  push:
    branches:
      - test-1
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout documentation source
        uses: actions/checkout@v4

      - name: Build container
        run: docker build . -f Dockerfile -t local

      - name: Generate en publish documentation
        run: docker run -v ${PWD}:/docs -e GITHUB_TOKEN=${GITHUB_TOKEN} --entrypoint "/bin/sh" local -c "/usr/bin/git config --global --add safe.directory /docs && mkdocs gh-deploy --force"
